name: Build APK + libv2ray

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone v2rayNG
      run: git clone https://github.com/2dust/v2rayNG.git

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 📥 качаем либу В ОТДЕЛЬНУЮ папку
    - name: Download libv2ray
      run: |
        mkdir -p output_libs/arm64-v8a
        mkdir -p output_libs/armeabi-v7a

        curl -L -o output_libs/arm64-v8a/libv2ray.so \
        https://github.com/2dust/v2rayNG/releases/download/1.8.5/libv2ray_arm64-v8a.so

        curl -L -o output_libs/armeabi-v7a/libv2ray.so \
        https://github.com/2dust/v2rayNG/releases/download/1.8.5/libv2ray_armeabi-v7a.so

    # ⚠️ билдим БЕЗ либы внутри APK
    - name: Build APK
      run: |
        cd v2rayNG
        chmod +x gradlew
        ./gradlew assembleDebug

    # 📦 APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: v2rayNG/app/build/outputs/apk/debug/*.apk

    # 📦 ЛИБКИ ОТДЕЛЬНО
    - name: Upload libv2ray
      uses: actions/upload-artifact@v4
      with:
        name: libv2ray
        path: output_libs/
